[package]
name = "typesize-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.9.0"
proc-macro2 = "1.0.69"
procout = "0.1.13"
quote = "1.0.33"
syn = "2.0.39"

[lib]
proc-macro = true

[features]
procout = ["procout/procout"]
