name: CI

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo test
        run: cargo test --all-features

  msrv-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Install cargo-minimal-versions
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack,cargo-minimal-versions

      - name: Install MSRV toolchain
        run: rustup toolchain install 1.65

      - name: Run Cargo test on MSRV
        run: cargo +1.65 minimal-versions test --features details

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Cargo clippy with no details, no libs
        run: cargo clippy -- --deny warnings

      - name: Run Cargo clippy with details, no libs
        run: cargo clippy --features details -- --deny warnings

      - name: Run Cargo clippy with details, no std, no libs
        run: cargo clippy --features details --no-default-features -- --deny warnings

      - name: Run Cargo clippy with no details, all libs
        run: cargo clippy --features dashmap,arrayvec,simd_json,halfbrown,parking_lot,serde_json,mini_moka,hashbrown,secrecy,chrono,nonmax,time,url,extract_map_01 -- --deny warnings

      - name: Run Cargo clippy with details, all libs
        run: cargo clippy --all-features -- --deny warnings
